backend:
  name: github
  repo: jingshow/jingshow.github.io
  branch: main
  auth_type: implicit

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "页面内容"
    files:
      - name: "home"
        label: "首页"
        file:"index.html"
        fields:
          - {label: "页面标题", name: "title", widget: "string"}
          - {label: "主体内容", name: "body", widget: "markdown"}
